overrides:
  simple-git: 3.36.0
  serialize-javascript: 7.0.4
  tar: 7.5.11
  flatted: 3.4.2
  "h3@^1.15.0": 1.15.9
  "h3@>=2.0.0-0 <2.0.1-rc.23": 2.0.1-rc.22
  "h3@2.0.1-rc.11": 2.0.1-rc.22
  "@nuxt/test-utils>h3-next": "npm:h3@2.0.1-rc.22"
  svgo: 4.0.1
  "vitest>vite": 7.3.2
  "h3>defu": 6.1.5
  "@nuxt/ui>defu": 6.1.5
  "nuxt-security>defu": 6.1.5
  "@nuxt/kit>defu": 6.1.5
  "@nuxt/test-utils>defu": 6.1.5
  "c12>defu": 6.1.5
  "untyped>defu": 6.1.5
  "anymatch>picomatch": 2.3.2
  "tinyglobby>picomatch": 4.0.4
  "@stylistic/eslint-plugin>picomatch": 4.0.4
  "unplugin>picomatch": 4.0.4
  "unimport>picomatch": 4.0.4
  "vitest>picomatch": 4.0.4
  "@xmldom/xmldom": 0.8.13
  "ajv>fast-uri": 3.1.2

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - bcrypt
  - esbuild

onlyBuiltDependencies:
  - bcrypt
  - esbuild
  - '@parcel/watcher'

allowBuilds:
  '@parcel/watcher': set this to true or false
  '@sentry/cli': set this to true or false
  bcrypt: set this to true or false
  cloudflared: set this to true or false
  esbuild: set this to true or false
  unrs-resolver: set this to true or false
  vue-demi: set this to true or false
