import type { ProductType } from '~~/app/types'

export type MetadataFieldControl = 'text' | 'textarea' | 'select' | 'switch' | 'date' | 'number'

export type MetadataFieldLevel = 'required' | 'recommended' | 'optional'

export interface MetadataFieldConfig {
  id: string
  label: string
  placeholder?: string
  control: MetadataFieldControl
  level: MetadataFieldLevel
  name?: string
  rows?: number
  options?: Array<{ label: string; value: string }>
  group: string
}

export type ProductMetadataLayout = Record<ProductType, MetadataFieldConfig[]>

export const PRODUCT_METADATA_LAYOUT: ProductMetadataLayout = {
  article: [
    {
      id: 'title',
      label: 'Título',
      control: 'text',
      level: 'required',
      name: 'title',
      placeholder: 'Título del documento…',
      group: 'Campos generales',
    },
    {
      id: 'authors',
      label: 'Autores',
      control: 'textarea',
      level: 'required',
      name: 'authors',
      rows: 3,
      placeholder: 'Separa cada autor con coma o salto de línea…',
      group: 'Campos generales',
    },
    {
      id: 'year',
      label: 'Año',
      control: 'text',
      level: 'recommended',
      name: 'year',
      placeholder: '2026…',
      group: 'Campos generales',
    },
    {
      id: 'institution',
      label: 'Institución',
      control: 'text',
      level: 'recommended',
      name: 'institution',
      placeholder: 'Universidad de Córdoba…',
      group: 'Campos generales',
    },
    {
      id: 'doi',
      label: 'DOI o referencia',
      control: 'text',
      level: 'recommended',
      name: 'doi',
      placeholder: '10.1234/ejemplo.2025.001…',
      group: 'Campos generales',
    },
    {
      id: 'keywords',
      label: 'Palabras clave',
      control: 'textarea',
      level: 'recommended',
      name: 'keywords',
      rows: 2,
      placeholder: 'innovación educativa, investigación, universidad…',
      group: 'Campos generales',
    },
    {
      id: 'notes',
      label: 'Notas',
      control: 'textarea',
      level: 'optional',
      name: 'notes',
      rows: 3,
      placeholder: 'Añade una aclaración útil para la revisión final…',
      group: 'Campos generales',
    },
    {
      id: 'journalName',
      label: 'Nombre de la revista',
      control: 'text',
      level: 'required',
      name: 'journalName',
      placeholder: 'Revista Colombiana de Educación…',
      group: 'Datos de la revista',
    },
    {
      id: 'volume',
      label: 'Volumen',
      control: 'text',
      level: 'recommended',
      name: 'volume',
      placeholder: '42…',
      group: 'Datos de la revista',
    },
    {
      id: 'issue',
      label: 'Número',
      control: 'text',
      level: 'recommended',
      name: 'issue',
      placeholder: '2…',
      group: 'Datos de la revista',
    },
    {
      id: 'pages',
      label: 'Páginas',
      control: 'text',
      level: 'recommended',
      name: 'pages',
      placeholder: '45-67…',
      group: 'Datos de la revista',
    },
    {
      id: 'issn',
      label: 'ISSN',
      control: 'text',
      level: 'recommended',
      name: 'issn',
      placeholder: '0123-4567…',
      group: 'Datos de la revista',
    },
    {
      id: 'articleType',
      label: 'Tipo de artículo',
      control: 'select',
      level: 'recommended',
      name: 'articleType',
      options: [
        { label: 'Original', value: 'original' },
        { label: 'Revisión', value: 'revision' },
        { label: 'Corto', value: 'corto' },
        { label: 'Carta', value: 'carta' },
        { label: 'Otro', value: 'otro' },
      ],
      group: 'Datos de la revista',
    },
    {
      id: 'indexing',
      label: 'Indexación',
      control: 'textarea',
      level: 'optional',
      name: 'indexing',
      rows: 2,
      placeholder: 'Scopus, WoS, Publindex, SciELO…',
      group: 'Datos de la revista',
    },
    {
      id: 'openAccess',
      label: 'Acceso abierto',
      control: 'switch',
      level: 'optional',
      name: 'openAccess',
      group: 'Datos de la revista',
    },
  ],
  thesis: [
    {
      id: 'title',
      label: 'Título',
      control: 'text',
      level: 'required',
      name: 'title',
      placeholder: 'Título del documento…',
      group: 'Campos generales',
    },
    {
      id: 'authors',
      label: 'Autores',
      control: 'textarea',
      level: 'required',
      name: 'authors',
      rows: 3,
      placeholder: 'Separa cada autor con coma o salto de línea…',
      group: 'Campos generales',
    },
    {
      id: 'year',
      label: 'Año',
      control: 'text',
      level: 'recommended',
      name: 'year',
      placeholder: '2026…',
      group: 'Campos generales',
    },
    {
      id: 'institution',
      label: 'Institución',
      control: 'text',
      level: 'recommended',
      name: 'institution',
      placeholder: 'Universidad de Córdoba…',
      group: 'Campos generales',
    },
    {
      id: 'doi',
      label: 'DOI o referencia',
      control: 'text',
      level: 'optional',
      name: 'doi',
      placeholder: '10.1234/ejemplo.2025.001…',
      group: 'Campos generales',
    },
    {
      id: 'keywords',
      label: 'Palabras clave',
      control: 'textarea',
      level: 'recommended',
      name: 'keywords',
      rows: 2,
      placeholder: 'innovación educativa, investigación, universidad…',
      group: 'Campos generales',
    },
    {
      id: 'notes',
      label: 'Notas',
      control: 'textarea',
      level: 'optional',
      name: 'notes',
      rows: 3,
      placeholder: 'Añade una aclaración útil para la revisión final…',
      group: 'Campos generales',
    },
    {
      id: 'thesisLevel',
      label: 'Nivel de tesis',
      control: 'select',
      level: 'required',
      name: 'thesisLevel',
      options: [
        { label: 'Pregrado', value: 'pregrado' },
        { label: 'Especialización', value: 'especializacion' },
        { label: 'Maestría', value: 'maestria' },
        { label: 'Doctorado', value: 'doctorado' },
      ],
      group: 'Datos de tesis',
    },
    {
      id: 'program',
      label: 'Programa',
      control: 'text',
      level: 'required',
      name: 'program',
      placeholder: 'Maestría en Innovación Educativa con Tecnología e IA…',
      group: 'Datos de tesis',
    },
    {
      id: 'director',
      label: 'Director(a)',
      control: 'text',
      level: 'recommended',
      name: 'director',
      placeholder: 'Nombre de la persona directora…',
      group: 'Datos de tesis',
    },
    {
      id: 'jurors',
      label: 'Jurados',
      control: 'textarea',
      level: 'recommended',
      name: 'jurors',
      rows: 2,
      placeholder: 'Separa cada jurado con coma o salto de línea…',
      group: 'Datos de tesis',
    },
    {
      id: 'university',
      label: 'Universidad',
      control: 'text',
      level: 'required',
      name: 'university',
      placeholder: 'Universidad de Córdoba…',
      group: 'Datos de tesis',
    },
    {
      id: 'faculty',
      label: 'Facultad',
      control: 'text',
      level: 'recommended',
      name: 'faculty',
      placeholder: 'Facultad de Educación…',
      group: 'Datos de tesis',
    },
    {
      id: 'degreeGrantor',
      label: 'Entidad que otorga el grado',
      control: 'text',
      level: 'recommended',
      name: 'degreeGrantor',
      placeholder: 'Nombre de la institución otorgante…',
      group: 'Datos de tesis',
    },
    {
      id: 'degreeName',
      label: 'Nombre del título',
      control: 'text',
      level: 'recommended',
      name: 'degreeName',
      placeholder: 'Magíster en…',
      group: 'Datos de tesis',
    },
    {
      id: 'areaOfKnowledge',
      label: 'Área de conocimiento',
      control: 'text',
      level: 'recommended',
      name: 'areaOfKnowledge',
      placeholder: 'Ciencias de la educación, ingeniería, etc.',
      group: 'Datos de tesis',
    },
    {
      id: 'modality',
      label: 'Modalidad',
      control: 'select',
      level: 'recommended',
      name: 'modality',
      options: [
        { label: 'Investigación', value: 'investigacion' },
        { label: 'Monografía', value: 'monografia' },
        { label: 'Proyecto aplicado', value: 'proyecto_aplicado' },
        { label: 'Otro', value: 'otro' },
      ],
      group: 'Datos de tesis',
    },
    {
      id: 'language',
      label: 'Idioma',
      control: 'text',
      level: 'recommended',
      name: 'language',
      placeholder: 'es, en…',
      group: 'Datos de tesis',
    },
    {
      id: 'pages',
      label: 'Número de páginas',
      control: 'number',
      level: 'recommended',
      name: 'pages',
      placeholder: '150…',
      group: 'Datos de tesis',
    },
    {
      id: 'projectCode',
      label: 'Código de proyecto',
      control: 'text',
      level: 'optional',
      name: 'projectCode',
      placeholder: 'Código del proyecto si aplica…',
      group: 'Datos de tesis',
    },
    {
      id: 'approvalDate',
      label: 'Fecha de aprobación',
      control: 'date',
      level: 'recommended',
      name: 'approvalDate',
      group: 'Datos de tesis',
    },
    {
      id: 'repositoryUrl',
      label: 'URL en repositorio',
      control: 'text',
      level: 'recommended',
      name: 'repositoryUrl',
      placeholder: 'https://repositorio.unicordoba.edu.co/handle/…',
      group: 'Datos de tesis',
    },
  ],
  conference_paper: [
    {
      id: 'title',
      label: 'Título',
      control: 'text',
      level: 'required',
      name: 'title',
      placeholder: 'Título del documento…',
      group: 'Campos generales',
    },
    {
      id: 'authors',
      label: 'Autores',
      control: 'textarea',
      level: 'required',
      name: 'authors',
      rows: 3,
      placeholder: 'Separa cada autor con coma o salto de línea…',
      group: 'Campos generales',
    },
    {
      id: 'year',
      label: 'Año',
      control: 'text',
      level: 'recommended',
      name: 'year',
      placeholder: '2026…',
      group: 'Campos generales',
    },
    {
      id: 'institution',
      label: 'Institución',
      control: 'text',
      level: 'recommended',
      name: 'institution',
      placeholder: 'Universidad de Córdoba…',
      group: 'Campos generales',
    },
    {
      id: 'doi',
      label: 'DOI o referencia',
      control: 'text',
      level: 'optional',
      name: 'doi',
      placeholder: '10.1234/ejemplo.2025.001…',
      group: 'Campos generales',
    },
    {
      id: 'keywords',
      label: 'Palabras clave',
      control: 'textarea',
      level: 'recommended',
      name: 'keywords',
      rows: 2,
      placeholder: 'innovación educativa, investigación, universidad…',
      group: 'Campos generales',
    },
    {
      id: 'notes',
      label: 'Notas',
      control: 'textarea',
      level: 'optional',
      name: 'notes',
      rows: 3,
      placeholder: 'Añade una aclaración útil para la revisión final…',
      group: 'Campos generales',
    },
    {
      id: 'eventName',
      label: 'Nombre del evento',
      control: 'text',
      level: 'required',
      name: 'eventName',
      placeholder: 'Congreso Internacional de…',
      group: 'Datos del evento',
    },
    {
      id: 'eventCity',
      label: 'Ciudad del evento',
      control: 'text',
      level: 'recommended',
      name: 'eventCity',
      placeholder: 'Montería…',
      group: 'Datos del evento',
    },
    {
      id: 'eventCountry',
      label: 'País del evento',
      control: 'text',
      level: 'recommended',
      name: 'eventCountry',
      placeholder: 'Colombia…',
      group: 'Datos del evento',
    },
    {
      id: 'eventDate',
      label: 'Fecha del evento',
      control: 'date',
      level: 'recommended',
      name: 'eventDate',
      group: 'Datos del evento',
    },
    {
      id: 'presentationType',
      label: 'Tipo de presentación',
      control: 'select',
      level: 'recommended',
      name: 'presentationType',
      options: [
        { label: 'Oral', value: 'oral' },
        { label: 'Póster', value: 'poster' },
        { label: 'Taller', value: 'workshop' },
        { label: 'Conferencia magistral', value: 'keynote' },
      ],
      group: 'Datos del evento',
    },
    {
      id: 'proceedingsTitle',
      label: 'Título de memorias',
      control: 'text',
      level: 'recommended',
      name: 'proceedingsTitle',
      placeholder: 'Memorias del congreso…',
      group: 'Datos de las memorias',
    },
    {
      id: 'isbn',
      label: 'ISBN',
      control: 'text',
      level: 'optional',
      name: 'isbn',
      placeholder: '978-958-00-0000-0…',
      group: 'Datos de las memorias',
    },
    {
      id: 'pages',
      label: 'Páginas',
      control: 'text',
      level: 'optional',
      name: 'pages',
      placeholder: '15-20…',
      group: 'Datos de las memorias',
    },
    {
      id: 'publisher',
      label: 'Editorial',
      control: 'text',
      level: 'optional',
      name: 'publisher',
      placeholder: 'Editorial o institución publicadora…',
      group: 'Datos de las memorias',
    },
  ],
  certificate: [
    {
      id: 'title',
      label: 'Título',
      control: 'text',
      level: 'required',
      name: 'title',
      placeholder: 'Título del documento…',
      group: 'Campos generales',
    },
    {
      id: 'authors',
      label: 'Autores',
      control: 'textarea',
      level: 'required',
      name: 'authors',
      rows: 3,
      placeholder: 'Separa cada autor con coma o salto de línea…',
      group: 'Campos generales',
    },
    {
      id: 'year',
      label: 'Año',
      control: 'text',
      level: 'recommended',
      name: 'year',
      placeholder: '2026…',
      group: 'Campos generales',
    },
    {
      id: 'institution',
      label: 'Institución',
      control: 'text',
      level: 'recommended',
      name: 'institution',
      placeholder: 'Universidad de Córdoba…',
      group: 'Campos generales',
    },
    {
      id: 'doi',
      label: 'DOI o referencia',
      control: 'text',
      level: 'optional',
      name: 'doi',
      placeholder: '10.1234/ejemplo.2025.001…',
      group: 'Campos generales',
    },
    {
      id: 'keywords',
      label: 'Palabras clave',
      control: 'textarea',
      level: 'optional',
      name: 'keywords',
      rows: 2,
      placeholder: 'formación, asistencia, certificación…',
      group: 'Campos generales',
    },
    {
      id: 'notes',
      label: 'Notas',
      control: 'textarea',
      level: 'optional',
      name: 'notes',
      rows: 3,
      placeholder: 'Añade una aclaración útil para la revisión final…',
      group: 'Campos generales',
    },
    {
      id: 'issuingEntity',
      label: 'Entidad emisora',
      control: 'text',
      level: 'required',
      name: 'issuingEntity',
      placeholder: 'Entidad o institución que emite el certificado…',
      group: 'Detalles del certificado',
    },
    {
      id: 'certificateType',
      label: 'Tipo de certificado',
      control: 'select',
      level: 'recommended',
      name: 'certificateType',
      options: [
        { label: 'Participación', value: 'participacion' },
        { label: 'Ponente', value: 'ponente' },
        { label: 'Asistencia', value: 'asistencia' },
        { label: 'Instructor', value: 'instructor' },
        { label: 'Otro', value: 'otro' },
      ],
      group: 'Detalles del certificado',
    },
    {
      id: 'relatedEvent',
      label: 'Evento relacionado',
      control: 'text',
      level: 'recommended',
      name: 'relatedEvent',
      placeholder: 'Nombre del evento o actividad…',
      group: 'Detalles del certificado',
    },
    {
      id: 'issueDate',
      label: 'Fecha de emisión',
      control: 'date',
      level: 'recommended',
      name: 'issueDate',
      group: 'Detalles del certificado',
    },
    {
      id: 'expirationDate',
      label: 'Fecha de vencimiento',
      control: 'date',
      level: 'optional',
      name: 'expirationDate',
      group: 'Detalles del certificado',
    },
    {
      id: 'hours',
      label: 'Horas certificadas',
      control: 'number',
      level: 'optional',
      name: 'hours',
      placeholder: '40…',
      group: 'Detalles del certificado',
    },
    {
      id: 'modality',
      label: 'Modalidad',
      control: 'select',
      level: 'optional',
      name: 'modality',
      options: [
        { label: 'Presencial', value: 'presencial' },
        { label: 'Virtual', value: 'virtual' },
        { label: 'Híbrida', value: 'hibrida' },
      ],
      group: 'Detalles del certificado',
    },
    {
      id: 'location',
      label: 'Lugar',
      control: 'text',
      level: 'optional',
      name: 'location',
      placeholder: 'Montería, Córdoba…',
      group: 'Detalles del certificado',
    },
  ],
  research_project: [
    {
      id: 'title',
      label: 'Título',
      control: 'text',
      level: 'required',
      name: 'title',
      placeholder: 'Título del documento…',
      group: 'Campos generales',
    },
    {
      id: 'authors',
      label: 'Autores',
      control: 'textarea',
      level: 'required',
      name: 'authors',
      rows: 3,
      placeholder: 'Separa cada autor con coma o salto de línea…',
      group: 'Campos generales',
    },
    {
      id: 'year',
      label: 'Año',
      control: 'text',
      level: 'recommended',
      name: 'year',
      placeholder: '2026…',
      group: 'Campos generales',
    },
    {
      id: 'institution',
      label: 'Institución',
      control: 'text',
      level: 'recommended',
      name: 'institution',
      placeholder: 'Universidad de Córdoba…',
      group: 'Campos generales',
    },
    {
      id: 'doi',
      label: 'DOI o referencia',
      control: 'text',
      level: 'optional',
      name: 'doi',
      placeholder: '10.1234/ejemplo.2025.001…',
      group: 'Campos generales',
    },
    {
      id: 'keywords',
      label: 'Palabras clave',
      control: 'textarea',
      level: 'recommended',
      name: 'keywords',
      rows: 2,
      placeholder: 'innovación educativa, investigación, universidad…',
      group: 'Campos generales',
    },
    {
      id: 'notes',
      label: 'Notas',
      control: 'textarea',
      level: 'optional',
      name: 'notes',
      rows: 3,
      placeholder: 'Añade una aclaración útil para la revisión final…',
      group: 'Campos generales',
    },
    {
      id: 'projectCode',
      label: 'Código de proyecto',
      control: 'text',
      level: 'required',
      name: 'projectCode',
      placeholder: 'Código interno o institucional del proyecto…',
      group: 'Datos del proyecto',
    },
    {
      id: 'projectStatus',
      label: 'Estado del proyecto',
      control: 'select',
      level: 'recommended',
      name: 'projectStatus',
      options: [
        { label: 'Activo', value: 'active' },
        { label: 'Completado', value: 'completed' },
        { label: 'Suspendido', value: 'suspended' },
      ],
      group: 'Datos del proyecto',
    },
    {
      id: 'fundingSource',
      label: 'Fuente de financiación',
      control: 'text',
      level: 'recommended',
      name: 'fundingSource',
      placeholder: 'Minciencias, convocatoria interna, cooperación…',
      group: 'Datos del proyecto',
    },
    {
      id: 'startDate',
      label: 'Fecha de inicio',
      control: 'date',
      level: 'recommended',
      name: 'startDate',
      group: 'Datos del proyecto',
    },
    {
      id: 'endDate',
      label: 'Fecha de cierre',
      control: 'date',
      level: 'optional',
      name: 'endDate',
      group: 'Datos del proyecto',
    },
    {
      id: 'principalInvestigatorName',
      label: 'Investigador principal',
      control: 'text',
      level: 'recommended',
      name: 'principalInvestigatorName',
      placeholder: 'Nombre completo del IP…',
      group: 'Datos del proyecto',
    },
    {
      id: 'coResearchers',
      label: 'Coinvestigadores',
      control: 'textarea',
      level: 'optional',
      name: 'coResearchers',
      rows: 2,
      placeholder: 'Separa cada nombre con coma o salto de línea…',
      group: 'Datos del proyecto',
    },
    {
      id: 'programOrCall',
      label: 'Programa o convocatoria',
      control: 'text',
      level: 'optional',
      name: 'programOrCall',
      placeholder: 'Nombre de la convocatoria o programa…',
      group: 'Datos del proyecto',
    },
    {
      id: 'budget',
      label: 'Presupuesto',
      control: 'number',
      level: 'optional',
      name: 'budget',
      placeholder: '25000000…',
      group: 'Datos del proyecto',
    },
  ],
  book: [
    {
      id: 'title',
      label: 'Título',
      control: 'text',
      level: 'required',
      name: 'title',
      placeholder: 'Título del libro…',
      group: 'Campos generales',
    },
    {
      id: 'authors',
      label: 'Autores',
      control: 'textarea',
      level: 'required',
      name: 'authors',
      rows: 3,
      placeholder: 'Separa cada autor con coma o salto de línea…',
      group: 'Campos generales',
    },
    {
      id: 'year',
      label: 'Año',
      control: 'text',
      level: 'recommended',
      name: 'year',
      placeholder: '2026…',
      group: 'Campos generales',
    },
    {
      id: 'institution',
      label: 'Institución',
      control: 'text',
      level: 'recommended',
      name: 'institution',
      placeholder: 'Universidad de Córdoba…',
      group: 'Campos generales',
    },
    {
      id: 'doi',
      label: 'DOI o referencia',
      control: 'text',
      level: 'optional',
      name: 'doi',
      placeholder: '10.1234/ejemplo.2025.001…',
      group: 'Campos generales',
    },
    {
      id: 'keywords',
      label: 'Palabras clave',
      control: 'textarea',
      level: 'recommended',
      name: 'keywords',
      rows: 2,
      placeholder: 'libro, investigación, educación…',
      group: 'Campos generales',
    },
    {
      id: 'notes',
      label: 'Notas',
      control: 'textarea',
      level: 'optional',
      name: 'notes',
      rows: 3,
      placeholder: 'Añade una aclaración útil para la revisión final…',
      group: 'Campos generales',
    },
    {
      id: 'bookPublisher',
      label: 'Editorial',
      control: 'text',
      level: 'required',
      name: 'bookPublisher',
      placeholder: 'Nombre de la editorial…',
      group: 'Datos del libro',
    },
    {
      id: 'bookIsbn',
      label: 'ISBN',
      control: 'text',
      level: 'recommended',
      name: 'bookIsbn',
      placeholder: '978-958-00-0000-0…',
      group: 'Datos del libro',
    },
    {
      id: 'bookEdition',
      label: 'Edición',
      control: 'text',
      level: 'optional',
      name: 'bookEdition',
      placeholder: '2da edición…',
      group: 'Datos del libro',
    },
    {
      id: 'bookCity',
      label: 'Ciudad de publicación',
      control: 'text',
      level: 'optional',
      name: 'bookCity',
      placeholder: 'Bogotá…',
      group: 'Datos del libro',
    },
    {
      id: 'bookCollection',
      label: 'Colección o serie',
      control: 'text',
      level: 'optional',
      name: 'bookCollection',
      placeholder: 'Colección Investigación y Docencia…',
      group: 'Datos del libro',
    },
    {
      id: 'bookTotalPages',
      label: 'Total de páginas',
      control: 'number',
      level: 'recommended',
      name: 'bookTotalPages',
      placeholder: '320…',
      group: 'Datos del libro',
    },
    {
      id: 'bookLanguage',
      label: 'Idioma',
      control: 'text',
      level: 'recommended',
      name: 'bookLanguage',
      placeholder: 'es, en…',
      group: 'Datos del libro',
    },
    {
      id: 'bookPublicationDate',
      label: 'Fecha de publicación',
      control: 'date',
      level: 'recommended',
      name: 'bookPublicationDate',
      group: 'Datos del libro',
    },
  ],
  book_chapter: [
    {
      id: 'title',
      label: 'Título del capítulo',
      control: 'text',
      level: 'required',
      name: 'title',
      placeholder: 'Título del capítulo…',
      group: 'Campos generales',
    },
    {
      id: 'authors',
      label: 'Autores',
      control: 'textarea',
      level: 'required',
      name: 'authors',
      rows: 3,
      placeholder: 'Separa cada autor con coma o salto de línea…',
      group: 'Campos generales',
    },
    {
      id: 'year',
      label: 'Año',
      control: 'text',
      level: 'recommended',
      name: 'year',
      placeholder: '2026…',
      group: 'Campos generales',
    },
    {
      id: 'institution',
      label: 'Institución',
      control: 'text',
      level: 'recommended',
      name: 'institution',
      placeholder: 'Universidad de Córdoba…',
      group: 'Campos generales',
    },
    {
      id: 'doi',
      label: 'DOI o referencia',
      control: 'text',
      level: 'optional',
      name: 'doi',
      placeholder: '10.1234/ejemplo.2025.001…',
      group: 'Campos generales',
    },
    {
      id: 'keywords',
      label: 'Palabras clave',
      control: 'textarea',
      level: 'recommended',
      name: 'keywords',
      rows: 2,
      placeholder: 'capítulo, investigación, educación…',
      group: 'Campos generales',
    },
    {
      id: 'notes',
      label: 'Notas',
      control: 'textarea',
      level: 'optional',
      name: 'notes',
      rows: 3,
      placeholder: 'Añade una aclaración útil para la revisión final…',
      group: 'Campos generales',
    },
    {
      id: 'chapterBookTitle',
      label: 'Título del libro',
      control: 'text',
      level: 'required',
      name: 'chapterBookTitle',
      placeholder: 'Libro donde aparece el capítulo…',
      group: 'Datos del capítulo',
    },
    {
      id: 'chapterNumber',
      label: 'Número de capítulo',
      control: 'text',
      level: 'optional',
      name: 'chapterNumber',
      placeholder: 'Capítulo 3…',
      group: 'Datos del capítulo',
    },
    {
      id: 'chapterPages',
      label: 'Páginas del capítulo',
      control: 'text',
      level: 'recommended',
      name: 'chapterPages',
      placeholder: '45-68…',
      group: 'Datos del capítulo',
    },
    {
      id: 'chapterEditors',
      label: 'Editores del libro',
      control: 'textarea',
      level: 'optional',
      name: 'chapterEditors',
      rows: 2,
      placeholder: 'Separa cada editor con coma o salto de línea…',
      group: 'Datos del capítulo',
    },
    {
      id: 'chapterPublisher',
      label: 'Editorial del libro',
      control: 'text',
      level: 'recommended',
      name: 'chapterPublisher',
      placeholder: 'Nombre de la editorial…',
      group: 'Datos del capítulo',
    },
    {
      id: 'chapterIsbn',
      label: 'ISBN del libro',
      control: 'text',
      level: 'optional',
      name: 'chapterIsbn',
      placeholder: '978-958-00-0000-0…',
      group: 'Datos del capítulo',
    },
    {
      id: 'chapterEdition',
      label: 'Edición del libro',
      control: 'text',
      level: 'optional',
      name: 'chapterEdition',
      placeholder: '1ra edición…',
      group: 'Datos del capítulo',
    },
    {
      id: 'chapterLanguage',
      label: 'Idioma',
      control: 'text',
      level: 'recommended',
      name: 'chapterLanguage',
      placeholder: 'es, en…',
      group: 'Datos del capítulo',
    },
    {
      id: 'chapterPublicationDate',
      label: 'Fecha de publicación',
      control: 'date',
      level: 'optional',
      name: 'chapterPublicationDate',
      group: 'Datos del capítulo',
    },
  ],
  technical_report: [
    {
      id: 'title',
      label: 'Título',
      control: 'text',
      level: 'required',
      name: 'title',
      placeholder: 'Título del reporte técnico…',
      group: 'Campos generales',
    },
    {
      id: 'authors',
      label: 'Autores',
      control: 'textarea',
      level: 'required',
      name: 'authors',
      rows: 3,
      placeholder: 'Separa cada autor con coma o salto de línea…',
      group: 'Campos generales',
    },
    {
      id: 'year',
      label: 'Año',
      control: 'text',
      level: 'recommended',
      name: 'year',
      placeholder: '2026…',
      group: 'Campos generales',
    },
    {
      id: 'institution',
      label: 'Institución',
      control: 'text',
      level: 'recommended',
      name: 'institution',
      placeholder: 'Universidad de Córdoba…',
      group: 'Campos generales',
    },
    {
      id: 'doi',
      label: 'DOI o referencia',
      control: 'text',
      level: 'optional',
      name: 'doi',
      placeholder: '10.1234/ejemplo.2025.001…',
      group: 'Campos generales',
    },
    {
      id: 'keywords',
      label: 'Palabras clave',
      control: 'textarea',
      level: 'recommended',
      name: 'keywords',
      rows: 2,
      placeholder: 'reporte, técnico, investigación…',
      group: 'Campos generales',
    },
    {
      id: 'notes',
      label: 'Notas',
      control: 'textarea',
      level: 'optional',
      name: 'notes',
      rows: 3,
      placeholder: 'Añade una aclaración útil para la revisión final…',
      group: 'Campos generales',
    },
    {
      id: 'reportNumber',
      label: 'Número de reporte',
      control: 'text',
      level: 'required',
      name: 'reportNumber',
      placeholder: 'TR-2026-014…',
      group: 'Datos del reporte',
    },
    {
      id: 'reportInstitution',
      label: 'Institución responsable',
      control: 'text',
      level: 'required',
      name: 'reportInstitution',
      placeholder: 'Institución o grupo emisor…',
      group: 'Datos del reporte',
    },
    {
      id: 'reportType',
      label: 'Tipo de reporte',
      control: 'select',
      level: 'recommended',
      name: 'reportType',
      options: [
        { label: 'Final', value: 'final' },
        { label: 'Intermedio', value: 'interim' },
        { label: 'White paper', value: 'white_paper' },
        { label: 'Manual', value: 'manual' },
        { label: 'Otro', value: 'other' },
      ],
      group: 'Datos del reporte',
    },
    {
      id: 'reportSponsor',
      label: 'Entidad financiadora',
      control: 'text',
      level: 'optional',
      name: 'reportSponsor',
      placeholder: 'Entidad patrocinadora…',
      group: 'Datos del reporte',
    },
    {
      id: 'reportPublicationDate',
      label: 'Fecha de publicación',
      control: 'date',
      level: 'recommended',
      name: 'reportPublicationDate',
      group: 'Datos del reporte',
    },
    {
      id: 'reportRevision',
      label: 'Versión/revisión',
      control: 'text',
      level: 'optional',
      name: 'reportRevision',
      placeholder: 'Rev. 2.1…',
      group: 'Datos del reporte',
    },
    {
      id: 'reportPages',
      label: 'Número de páginas',
      control: 'number',
      level: 'optional',
      name: 'reportPages',
      placeholder: '85…',
      group: 'Datos del reporte',
    },
    {
      id: 'reportRepositoryUrl',
      label: 'URL del repositorio',
      control: 'text',
      level: 'optional',
      name: 'reportRepositoryUrl',
      placeholder: 'https://repositorio... ',
      group: 'Datos del reporte',
    },
    {
      id: 'reportAreaOfKnowledge',
      label: 'Área de conocimiento',
      control: 'text',
      level: 'optional',
      name: 'reportAreaOfKnowledge',
      placeholder: 'Ingeniería de software…',
      group: 'Datos del reporte',
    },
    {
      id: 'reportLanguage',
      label: 'Idioma',
      control: 'text',
      level: 'optional',
      name: 'reportLanguage',
      placeholder: 'es, en…',
      group: 'Datos del reporte',
    },
  ],
  software: [
    {
      id: 'title',
      label: 'Nombre del software',
      control: 'text',
      level: 'required',
      name: 'title',
      placeholder: 'Nombre del software…',
      group: 'Campos generales',
    },
    {
      id: 'authors',
      label: 'Autores',
      control: 'textarea',
      level: 'required',
      name: 'authors',
      rows: 3,
      placeholder: 'Separa cada autor con coma o salto de línea…',
      group: 'Campos generales',
    },
    {
      id: 'year',
      label: 'Año',
      control: 'text',
      level: 'recommended',
      name: 'year',
      placeholder: '2026…',
      group: 'Campos generales',
    },
    {
      id: 'institution',
      label: 'Institución',
      control: 'text',
      level: 'recommended',
      name: 'institution',
      placeholder: 'Universidad de Córdoba…',
      group: 'Campos generales',
    },
    {
      id: 'doi',
      label: 'DOI o referencia',
      control: 'text',
      level: 'optional',
      name: 'doi',
      placeholder: '10.1234/ejemplo.2025.001…',
      group: 'Campos generales',
    },
    {
      id: 'keywords',
      label: 'Palabras clave',
      control: 'textarea',
      level: 'recommended',
      name: 'keywords',
      rows: 2,
      placeholder: 'software, repositorio, desarrollo…',
      group: 'Campos generales',
    },
    {
      id: 'notes',
      label: 'Notas',
      control: 'textarea',
      level: 'optional',
      name: 'notes',
      rows: 3,
      placeholder: 'Añade una aclaración útil para la revisión final…',
      group: 'Campos generales',
    },
    {
      id: 'softwareVersion',
      label: 'Versión',
      control: 'text',
      level: 'required',
      name: 'softwareVersion',
      placeholder: 'v1.2.0…',
      group: 'Datos del software',
    },
    {
      id: 'softwareReleaseDate',
      label: 'Fecha de liberación',
      control: 'date',
      level: 'recommended',
      name: 'softwareReleaseDate',
      group: 'Datos del software',
    },
    {
      id: 'softwareRepositoryUrl',
      label: 'Repositorio',
      control: 'text',
      level: 'recommended',
      name: 'softwareRepositoryUrl',
      placeholder: 'https://github.com/organizacion/proyecto',
      group: 'Datos del software',
    },
    {
      id: 'softwareLicense',
      label: 'Licencia',
      control: 'text',
      level: 'recommended',
      name: 'softwareLicense',
      placeholder: 'MIT, GPL-3.0…',
      group: 'Datos del software',
    },
    {
      id: 'softwareProgrammingLanguage',
      label: 'Lenguaje principal',
      control: 'text',
      level: 'optional',
      name: 'softwareProgrammingLanguage',
      placeholder: 'TypeScript, Python…',
      group: 'Datos del software',
    },
    {
      id: 'softwarePlatform',
      label: 'Plataforma',
      control: 'text',
      level: 'optional',
      name: 'softwarePlatform',
      placeholder: 'Web, Desktop, Android…',
      group: 'Datos del software',
    },
    {
      id: 'softwareType',
      label: 'Tipo de software',
      control: 'select',
      level: 'recommended',
      name: 'softwareType',
      options: [
        { label: 'Escritorio', value: 'desktop' },
        { label: 'Web', value: 'web' },
        { label: 'Móvil', value: 'mobile' },
        { label: 'Librería', value: 'library' },
        { label: 'Otro', value: 'other' },
      ],
      group: 'Datos del software',
    },
    {
      id: 'softwareRegistrationNumber',
      label: 'Número de registro',
      control: 'text',
      level: 'optional',
      name: 'softwareRegistrationNumber',
      placeholder: 'Registro oficial si aplica…',
      group: 'Datos del software',
    },
  ],
  patent: [
    {
      id: 'title',
      label: 'Título de la patente',
      control: 'text',
      level: 'required',
      name: 'title',
      placeholder: 'Título de la invención…',
      group: 'Campos generales',
    },
    {
      id: 'authors',
      label: 'Autores',
      control: 'textarea',
      level: 'required',
      name: 'authors',
      rows: 3,
      placeholder: 'Separa cada autor con coma o salto de línea…',
      group: 'Campos generales',
    },
    {
      id: 'year',
      label: 'Año',
      control: 'text',
      level: 'recommended',
      name: 'year',
      placeholder: '2026…',
      group: 'Campos generales',
    },
    {
      id: 'institution',
      label: 'Institución',
      control: 'text',
      level: 'recommended',
      name: 'institution',
      placeholder: 'Universidad de Córdoba…',
      group: 'Campos generales',
    },
    {
      id: 'doi',
      label: 'DOI o referencia',
      control: 'text',
      level: 'optional',
      name: 'doi',
      placeholder: 'Número de publicación o referencia…',
      group: 'Campos generales',
    },
    {
      id: 'keywords',
      label: 'Palabras clave',
      control: 'textarea',
      level: 'recommended',
      name: 'keywords',
      rows: 2,
      placeholder: 'patente, invención, propiedad intelectual…',
      group: 'Campos generales',
    },
    {
      id: 'notes',
      label: 'Notas',
      control: 'textarea',
      level: 'optional',
      name: 'notes',
      rows: 3,
      placeholder: 'Añade una aclaración útil para la revisión final…',
      group: 'Campos generales',
    },
    {
      id: 'patentOffice',
      label: 'Oficina de patentes',
      control: 'text',
      level: 'required',
      name: 'patentOffice',
      placeholder: 'SIC, USPTO, EPO…',
      group: 'Datos de patente',
    },
    {
      id: 'patentApplicationNumber',
      label: 'Número de solicitud',
      control: 'text',
      level: 'required',
      name: 'patentApplicationNumber',
      placeholder: 'Número de radicado…',
      group: 'Datos de patente',
    },
    {
      id: 'patentPublicationNumber',
      label: 'Número de publicación',
      control: 'text',
      level: 'optional',
      name: 'patentPublicationNumber',
      placeholder: 'Publicación oficial…',
      group: 'Datos de patente',
    },
    {
      id: 'patentApplicationDate',
      label: 'Fecha de solicitud',
      control: 'date',
      level: 'recommended',
      name: 'patentApplicationDate',
      group: 'Datos de patente',
    },
    {
      id: 'patentPublicationDate',
      label: 'Fecha de publicación',
      control: 'date',
      level: 'optional',
      name: 'patentPublicationDate',
      group: 'Datos de patente',
    },
    {
      id: 'patentGrantDate',
      label: 'Fecha de concesión',
      control: 'date',
      level: 'optional',
      name: 'patentGrantDate',
      group: 'Datos de patente',
    },
    {
      id: 'patentStatus',
      label: 'Estado',
      control: 'select',
      level: 'recommended',
      name: 'patentStatus',
      options: [
        { label: 'Solicitada', value: 'submitted' },
        { label: 'Publicada', value: 'published' },
        { label: 'Concedida', value: 'granted' },
        { label: 'Expirada', value: 'expired' },
      ],
      group: 'Datos de patente',
    },
    {
      id: 'patentAssignee',
      label: 'Titular',
      control: 'text',
      level: 'optional',
      name: 'patentAssignee',
      placeholder: 'Persona o institución titular…',
      group: 'Datos de patente',
    },
    {
      id: 'patentInventors',
      label: 'Inventores',
      control: 'textarea',
      level: 'optional',
      name: 'patentInventors',
      rows: 2,
      placeholder: 'Separa cada inventor con coma o salto de línea…',
      group: 'Datos de patente',
    },
    {
      id: 'patentCountry',
      label: 'País',
      control: 'text',
      level: 'optional',
      name: 'patentCountry',
      placeholder: 'Colombia, Estados Unidos…',
      group: 'Datos de patente',
    },
    {
      id: 'patentClassification',
      label: 'Clasificación (IPC/CPC)',
      control: 'text',
      level: 'optional',
      name: 'patentClassification',
      placeholder: 'G06F 3/01…',
      group: 'Datos de patente',
    },
  ],
}
